### PR TITLE
Disable chruby_auto if RUBY_AUTO_DISABLE is set

### PR DESCRIPTION
**Pull request by sheldonh**
Fixes postmodern/chruby#337

### CODE REVIEW

**Comment by postmodern** [comment]
Why can't you simply not load `auto.sh`, or is another program loading both by default? It's a separate file specifically to allow users to opt-out.

**Comment by sheldonh** [comment]
I can edit the `/etc/profile.d/chruby.sh` that the setup helper writes. It's just root-owned, so I figured it would be nice for individual users to have a way to opt out.

**Comment by postmodern** [comment]
@sheldonh which setup helper? Perhaps we could make it more configurable.

**Comment by sheldonh** [comment]
Oh, sorry. I'm referring to the [setup.sh script](https://github.com/postmodern/chruby/blob/4572384143f3ee40c59a164635a0e773be3a58ac/scripts/setup.sh) referred to from the [README](https://github.com/postmodern/chruby/blob/26df12ca8741db54016ac4bffbd011e79cc3009c/README.md#setupsh).

**Comment by postmodern** [comment]
@sheldonh ah hmm. Did someone else run the script and you don't have sudo privileges?

**Comment by sheldonh** [comment]
Nope. I ran the script and I have root privilege. As the only user on my workstation, it's a non-issue. I can just edit the file (or not run it in the first place, sourcing just `chruby.sh` in my personal `.bashrc`).

My thinking went like this:

* The documentation advertises a chruby setup script.
* The chruby setup script activates `chruby_auto`, system-wide.
* This makes `chruby_auto` something of a default.
* Other people might expect that default.
* But I don't like it.
* So on multi-user systems, let unprivileged people who don't like it, disable it for themselves.

If you don't like the idea, you can bin it. I won't be offended. Chruby is a great little tool. Thanks.

**Comment by postmodern** [comment]
I'm thinking of adding options to `setup.sh` to enable/disable things. `--no-auto` or maybe `--no-global`.

**Pull request closed without merging**
