### PR TITLE
Add basic tab completion support for Bash and Zsh

### LINKED ISSUE #27: Add bash completion
This works for me:

``` bash
__complete_chruby() {
  local cur rubie basenames
  typeset -a basenames
  cur="${COMP_WORDS[COMP_CWORD]}"
  for rubie in ${RUBIES[@]}; do
    basenames+=($(basename $rubie))
  done
  COMPREPLY=( $(compgen -W "${basenames[*]}" -- ${cur}) )
}
complete -F __complete_chruby chruby
```

I added it to chruby.sh, but maybe you want to do it differently to also support zsh?

### PR DESCRIPTION
**Pull request by callahad**
Fixes #27

### CODE REVIEW

**Comment by postmodern** [comment]
Maybe we could use a `coproc` and explicitly send in the tabs? http://wiki.bash-hackers.org/syntax/keywords/coproc

**Comment by kbrock** [comment]
1. Is there a convention for these to be named like `_chrubycomplete`?
2. Thanks for this code, it is better than the one I had defined.

**Comment by FranklinYu** [comment]
Is this Pull Request blocked by lack of test?

> Is there a convention for these to be named like `_chrubycomplete`?

I think it should be `_chruby`. Bash by default [looks up completion by command name](https://github.com/scop/bash-completion/blob/fb46fed657d6b6575974b2fd5a9b6529ed2472b7/bash_completion#L2083-L2112) (warning: large file, syntax-highlight not working).

**Comment by FranklinYu** [comment]
In addition I think it's better to put Bash and Zsh completions in different files. This way package maintainers can link Bash completion to `/etc/bash_completion.d/`, and link Zsh completion to `/usr/share/zsh/vendor-completions/`, avoiding the problem of `compdef` at all.

**Comment by FranklinYu** [comment]
Hi @callahad are you still interested in this PR? If not I can take it over.

**Comment by callahad** [comment]
It's all yours :) thank you for picking it up!

**Pull request closed without merging**
